[package]
name = "paxos"
version = "0.1.0"
authors = ["DetectivePikachu <soubhikdeb1994@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7"
log = "0.4"